name: release
on:
  release:
    types: [released]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          ./release-preview.sh ${{ env.RELEASE_VERSION }}
          cd tangerine-preview
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
